server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/notes
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret:
    key: 9147b4f15b4157f56c414d1cd3436eba5e50833aca2d47a7625c1d07aad9e2f9
